{{- if .Values.chatUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chatUi.service.name }}
  labels:
    app: {{ .Values.chatUi.name }}
    app.kubernetes.io/name: {{ .Values.chatUi.name }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.chatUi.service.port }}
    targetPort: {{ .Values.chatUi.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.chatUi.name }}
{{- end }}
