{{- if and .Values.chatUi.enabled .Values.chatUi.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.chatUi.route.name }}
  labels:
    app: {{ .Values.chatUi.name }}
    app.kubernetes.io/name: {{ .Values.chatUi.name }}
    app.kubernetes.io/component: frontend
spec:
  to:
    kind: Service
    name: {{ .Values.chatUi.service.name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.chatUi.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.chatUi.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
