{{- if .Values.langgraphFastapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.langgraphFastapi.service.name }}
  labels:
    app: {{ .Values.langgraphFastapi.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.langgraphFastapi.name }}
  ports:
  - port: {{ .Values.langgraphFastapi.service.port }}
    targetPort: {{ .Values.langgraphFastapi.service.targetPort }}
    protocol: TCP
    name: http
{{- end }}
