apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-fastapi
  labels:
    app: langgraph-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langgraph-fastapi
  template:
    metadata:
      labels:
        app: langgraph-fastapi
    spec:
      containers:
      - name: langgraph-fastapi
        image: quay.io/bluesman/langgraph-fastapi:1.0.0
        imagePullPolicy: Always
        env:
        - name: LLAMA_STACK_BASE_URL
          value: http://llamastackdistribution-sample-service:8321
        - name: INFERENCE_MODEL
          value: vllm/llama-4-scout-17b-16e-w4a16
        - name: API_KEY
          value: fake
        - name: CUSTOMER_MCP_SERVER_URL
          value: http://mcp-customer-service:9001/mcp
        - name: FINANCE_MCP_SERVER_URL
          value: http://mcp-finance-service:9002/mcp

        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
