apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-customer
  labels:
    app: postgresql-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-customer
  template:
    metadata:
      labels:
        app: postgresql-customer
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel9/postgresql-15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
              name: postgres-cust
          env:
            - name: POSTGRESQL_USER
              value: customer
            - name: POSTGRESQL_PASSWORD
              value: customer
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: fantaco_customer
          volumeMounts:
            - name: postgres-customer-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-customer-data
          emptyDir: {}