{{- if .Values.customer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fantaco-customer-config
  labels:
    app: {{ .Values.customer.name }}
data:
  database.url: {{ .Values.customer.database.url | quote }}
  database.username: {{ .Values.customer.database.username | quote }}
  application.properties: |
    spring.jpa.hibernate.ddl-auto={{ .Values.customer.jpa.hibernate.ddlAuto }}
    spring.jpa.show-sql={{ .Values.customer.jpa.showSql }}
    logging.level.com.customer={{ .Values.customer.logging.level }}
{{- end }}
