{{- if .Values.customer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fantaco-customer-secret
type: Opaque
stringData:
  database.password: {{ .Values.customer.database.password | quote }}
{{- end }}
