{{- if and .Values.customer.enabled .Values.customer.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.customer.route.name }}
  labels:
    app: {{ .Values.customer.name }}
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.customer.route.tls.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.customer.route.tls.termination }}
  to:
    kind: Service
    name: {{ .Values.customer.service.name }}
    weight: 100
{{- end }}
