{{- if .Values.finance.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fantaco-finance-secret
type: Opaque
stringData:
  database.password: {{ .Values.finance.database.password | quote }}
{{- end }}
