{{- if .Values.postgresql.finance.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.finance.service.name }}
  labels:
    app: {{ .Values.postgresql.finance.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.finance.service.port }}
      targetPort: {{ .Values.postgresql.finance.service.port }}
      protocol: TCP
      name: postgres-fin
  selector:
    app: {{ .Values.postgresql.finance.name }}
{{- end }}
