{{- if .Values.postgresql.customer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.customer.service.name }}
  labels:
    app: {{ .Values.postgresql.customer.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.customer.service.port }}
      targetPort: postgres-cust
      protocol: TCP
      name: postgres-cust
  selector:
    app: {{ .Values.postgresql.customer.name }}
{{- end }}
