kind: ConfigMap
apiVersion: v1
metadata:
  name: gen-ai-aa-mcp-servers
  namespace: redhat-ods-applications
data:
  Customer-MCP-Server: |
    {
      "url": "https://mcp-customer-route-agent-user1.apps.ocp.cpkts.sandbox29.opentlc.com/mcp",
      "description": "Customer MCP Server",
      "logo": "https://www.svgrepo.com/show/374619/customers.svg"
    }
  Finance-MCP-Server: |
    {
      "url": "https://mcp-finance-route-agent-user1.apps.ocp.cpkts.sandbox29.opentlc.com/mcp",
      "description": "Finance MCP Server",
      "logo": "https://www.svgrepo.com/show/448002/financial-services.svg"
    }
