apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: langgraph-fastapi
  labels:
    app: langgraph-fastapi
spec:
  to:
    kind: Service
    name: langgraph-fastapi
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
